# -*- coding: utf-8 -*-
"""remove_blank

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UZx-I6KgyT19KTxkh0Lw9AL2DHTlmz4j
"""

# !pip install pypdf

from PyPDF2 import PdfReader, PdfWriter
# import requests
# from pathlib import Path
import os

remote_files = []
this_dir = "type_3"
for x in os.listdir(this_dir):
    if x.endswith(".pdf"):
        remote_files.append(x)

# os.mkdir('./trimmed_pdfs/')

print(remote_files)

for r in remote_files:
  output_writer = PdfWriter()
  # response = requests.get("https://github.com/mkane2/baptisms/raw/main/pdfs/type_3/" + r)
  # filename = Path('temp.pdf')
  # filename.write_bytes(response.content)
  reader = PdfReader(this_dir + "/" + r)
  # page = reader.pages[3]
  for page in reader.pages:
    if len(page.extract_text().strip()) >= 4:
      output_writer.add_page(page)
      print(len(page.extract_text().strip()))
    else:
      print("blank")
  # os.remove(filename)

  with open("trimmed_pdfs/" + r, "wb") as outfile:
          output_writer.write(outfile)

# import shutil

# shutil.make_archive("trimmed_pdfs", 'zip', "trimmed_pdfs")